layout_spectrum: 0.9802867
color:
  saturation: 0.8387097
  lightness: 0.5089605
  brandStrength: 0.9318997
  brandColors:
    - '#15150C'
    - '#9A5C03'
    - '#FBCF4B'
    - '#D79A1F'
    - '#BE6641'
  rhythmicContrast: 0.7114695
typography_spectrum: 0.2401434
name: el seco° comida ecuatoriana
